DNSBLServers:
 - "dnsbl.proxybl.org"
 - "socks.dnsbl.sorbs.net"
 - "misc.dnsbl.sorbs.net"
 - "xbl.spamhaus.org"
 - "cbl.abuseat.org"
 - "dnsbl.njabl.org"
 - "dnsbl.ahbl.org"
 - "ircbl.ahbl.org"
Whitelist:
 - "127.0.0.1"